volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: artembarsukov/foodgram_backend
    env_file: .env     
    volumes:
    - static:/backend_static/
    - media:/app/media/
    depends_on:
     - db

  frontend:
    image: artembarsukov/foodgram_frontend      
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    image: artembarsukov/foodgram_nginx
    ports:
      - "8000:80"
    volumes:      
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
